Spirillen patch 1
Phishing-Database/.github pull request #2
Opened 2024-12-18 12:32 UTC by spirillen

Commit for preview and properly a lot of git issues adding this on to the renamed branch

This commits

- issue templates
- README.md
- .gitignore

Please add any comments for enhancement

2024-12-18 16:56 UTC, g0d33p3rsec requested changes
Looks good.  I only see a couple of minor grammatical edits.

2024-12-18 16:56 UTC, g0d33p3rsec commented on profile/README.md
> +The Phishing database project aim's to provide up-to-date list of domains and URI there is hosting phishing contents.
This sentence could use a couple of minor grammatical edits, I would adjust it to something like "The Phishing database project's aim is to provide an up-to-date list of domains and URIs that are hosting phishing contents."

Another possibility would be to omit the apostrophe entirely, "The Phishing database project aims..."

2024-12-18 16:56 UTC, g0d33p3rsec commented on profile/README.md
> +In the following table, you'll find links to our datasets and it's checksum.
You can safely omit the apostrophe for "it's."

2024-12-18 16:57 UTC, g0d33p3rsec approved these changes

2024-12-18 16:57 UTC, g0d33p3rsec approved these changes

2024-12-18 18:45 UTC, spirillen commented on profile/README.md
> +The Phishing database project aim's to provide up-to-date list of domains and URI there is hosting phishing contents.
Accepted 👍🏻 thanks for the comment.

2024-12-18 18:47 UTC, spirillen commented on profile/README.md
> +In the following table, you'll find links to our datasets and it's checksum.
Accepted 👍🏻 thanks for the comment.

Both comments should be applied by now

2024-12-20 06:22 UTC, spirillen commented
@funilrys and @mitchellkrogza any comments? so we can get on with the welcome page and close https://github.com/Phishing-Database/dev-center/issues/2

2024-12-24 16:11 UTC, closed without merging